spring:
  application:
    name: ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/tbank
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

